# sample workflow
name : Sample
on:
  push:
    branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to the User
        run: echo "Hello Everyone"

      - name: Saying hello to current user
        run: echo "hello $USER"
